version: "3.8"

services:
  v2ray:
    container_name: v2ray
    image: ghcr.io/getimages/v2fly-core:v4.45.2
    restart: always
    environment:
      - v2ray.vmess.aead.forced=false
    ports:
      - "1310:1310"
    volumes:
      - ./config.json:/etc/v2ray/config.json
      - ./logs:/var/log/v2ray/
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
